### ISSUE TITLE
Error '"org.datanucleus" is already registered.' if maven repo is symbolic link

### ISSUE THREAD

**Issue by julianhyde** [datanucleus/datanucleus-maven-plugin#10]
If maven repository is a symbolic link (or has symbolic link somewhere along its path), datanucleus-maven-plugin fails.

You can reproduce with Hive:

```
$ mkdir /tmp/repository
$ ln -s /tmp/repository /tmp/repository2
$ cd ~/dev
$ git clone https://git-wip-us.apache.org/repos/asf/hive.git
$ cd hive
$ mvn  package -DskipTests -Dmaven.repo.local=/tmp/repository2

...

[INFO] Reactor Summary:
[INFO] 
[INFO] Hive .............................................. SUCCESS [ 17.412 s]
[INFO] Hive Shims Common ................................. SUCCESS [ 59.582 s]
[INFO] Hive Shims 0.23 ................................... SUCCESS [ 24.419 s]
[INFO] Hive Shims Scheduler .............................. SUCCESS [  0.625 s]
[INFO] Hive Shims ........................................ SUCCESS [  0.353 s]
[INFO] Hive Storage API .................................. SUCCESS [  3.589 s]
[INFO] Hive Common ....................................... SUCCESS [ 27.321 s]
[INFO] Hive Service RPC .................................. SUCCESS [  6.676 s]
[INFO] Hive Serde ........................................ SUCCESS [  5.955 s]
[INFO] Hive Standalone Metastore ......................... FAILURE [ 12.199 s]
[INFO] Hive Metastore .................................... SKIPPED
[INFO] Hive Vector-Code-Gen Utilities .................... SKIPPED
[INFO] Hive Llap Common .................................. SKIPPED
[INFO] Hive Llap Client .................................. SKIPPED
[INFO] Hive Llap Tez ..................................... SKIPPED
[INFO] Spark Remote Client ............................... SKIPPED
[INFO] Hive Query Language ............................... SKIPPED
[INFO] Hive Llap Server .................................. SKIPPED
[INFO] Hive Service ...................................... SKIPPED
[INFO] Hive Accumulo Handler ............................. SKIPPED
[INFO] Hive JDBC ......................................... SKIPPED
[INFO] Hive Beeline ...................................... SKIPPED
[INFO] Hive CLI .......................................... SKIPPED
[INFO] Hive Contrib ...................................... SKIPPED
[INFO] Hive Druid Handler ................................ SKIPPED
[INFO] Hive HBase Handler ................................ SKIPPED
[INFO] Hive JDBC Handler ................................. SKIPPED
[INFO] Hive HCatalog ..................................... SKIPPED
[INFO] Hive HCatalog Core ................................ SKIPPED
[INFO] Hive HCatalog Pig Adapter ......................... SKIPPED
[INFO] Hive HCatalog Server Extensions ................... SKIPPED
[INFO] Hive HCatalog Webhcat Java Client ................. SKIPPED
[INFO] Hive HCatalog Webhcat ............................. SKIPPED
[INFO] Hive HCatalog Streaming ........................... SKIPPED
[INFO] Hive HPL/SQL ...................................... SKIPPED
[INFO] Hive Llap External Client ......................... SKIPPED
[INFO] Hive Shims Aggregator ............................. SKIPPED
[INFO] Hive TestUtils .................................... SKIPPED
[INFO] Hive Packaging .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:39 min
[INFO] Finished at: 2017-09-05T12:08:35-08:00
[INFO] Final Memory: 109M/2311M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.datanucleus:datanucleus-maven-plugin:3.3.0-release:enhance (default) on project hive-standalone-metastore: Error executing DataNucleus tool org.datanucleus.enhancer.DataNucleusEnhancer: InvocationTargetException: Plugin (Bundle) "org.datanucleus" is already registered. Ensure you dont have multiple JAR versions of the same plugin in the classpath. The URL "file:/tmp/repository2/org/datanucleus/datanucleus-core/4.1.17/datanucleus-core-4.1.17.jar" is already registered, and you are trying to register an identical plugin located at URL "file:/tmp/repository/org/datanucleus/datanucleus-core/4.1.17/datanucleus-core-4.1.17.jar." -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hive-standalone-metastore

```

You can also reproduce it without `-Dmaven.repo.local` (if you don't mind trashing your local repo).

An email thread from a while ago was clearly running into the same problem: http://thread.gmane.org/gmane.comp.java.hadoop.hive.user/13953

**Comment by andyjefferson** [comment]
Datanucleus simply informs you of multiple jars in the classpath. Solution is to remove dups. Also the versions stated are not supported, so upgrade to the latest. Thx

Sadly we do not have resource to run non-standard tests, i.e non-datanucleus software included.

**Comment by julianhyde** [comment]
To be clear: are you claiming that this is not a bug? Do you believe that is fixed in the latest version?

There are no duplicates on the classpath, but just multiple paths to the same file. The classpath in this case is /tmp/repository2. Something internal to datanucleus (or perhaps maven) is expanding the classpath, seeing two occurrences of the same file via different paths, and claiming that these are duplicates.

Regarding test case. I don't have time to create a minimal test case. I thought you'd like to know about this bug, so I provided a test case that someone could execute if they didn't believe the bug was real. If someone fixes the bug of course they should create a better more minimal test case. I don't need a fix, because now I've figured out the cause, I have a workaround. It's a bit inconvenient that ~/.m2/repository has to be on the same filesystem as ~/.m2, but I can live with it. I logged a bug just so that the next person to run into this would be aware of the workaround.

**Comment by andyjefferson** [comment]
DataNucleus jars have an extension mechanism. datanucleus-core plugin handler will call getResources for "plugin.xml". You have multiple representing the same thing (datanucleus-core.jar). Having a check for such a thing makes perfect sense, since the user may expect to be using one version and have another. Your case is simply that you have 2 of the same, and so you should remove one. At runtime people can specify persistence properties such as datanucleus.plugin.pluginRegistryBundleCheck to decide what happens in this situation. 

But again, the versions you quote are not supported anyway, nor is this a problem with the DN Maven plugin (where it is raised). Marking as "won't fix".

Testcases are defined in http://www.datanucleus.org/documentation/problem_reporting.html.

**Comment by gtskaushik** [comment]
Faced the same issue today. When I have the maven repo as a symbolic link, it creates a problem

**Comment by andyjefferson** [comment]
So in summary you just want to state the same as the OP? 
The answer is simple, read my responses, and if that doesn't meet with your satisfaction then you get the code and develop something; this is why code is open source.

**Comment by gtskaushik** [comment]
I did the following to solve the issue for myself:-
1. Removed the symbolic link
2. Copied the data from my maven repo into ~/.m2/repository
Post this it was not throwing any error. But when we create a symbolic link, it complains that it is already registered in following locations:-
a. ~/.m2/repository (Symbolic link)
b. Actual Maven repo
So, though there is only one entry the presence of symbolic link cause a problem for the data-nucleus plugin.

Though I may not be able to work on this, I wanted to keep this as record so that someone who is looking for a solution will be thankful.

**Comment by theosib-amazon** [comment]
I'm running into a similar problem, but my "~/.m2/repository" is NOT a symlink. Despite that, I get an error like what y'all were seeing two years ago.

```
[ERROR] Failed to execute goal org.datanucleus:datanucleus-maven-plugin:3.3.0-release:enhance (default) on project hive-metastore: Error executing DataNucleus tool org.datanucleus.enhancer.DataNucleusEnhancer: InvocationTargetException: Plugin (Bundle) "org.datanucleus" is already registered. Ensure you dont have multiple JAR versions of the same plugin in the classpath. The URL "file:/home/theosib/.m2/repository/org/datanucleus/datanucleus-core/3.2.10/datanucleus-core-3.2.10.jar" is already registered, and you are trying to register an identical plugin located at URL "file:/local/home/theosib/.m2/repository/org/datanucleus/datanucleus-core/3.2.10/datanucleus-core-3.2.10.jar." -> [Help 1]
```

**Comment by andyjefferson** [comment]
As the docs say v3.x hasn't been supported for many years. Debug your problem, perhaps using "maven --debug".
