### ISSUE TITLE
Provide additional goals to enhance test code

### ISSUE THREAD

**Issue by danhaywood** [datanucleus/datanucleus-maven-plugin#5]
When writing some integration tests, I needed a dummy entity for those tests, to reside under src/test/java.  However the 'enhance' and 'enhance-check' goals can only be used to run against code with 'compile' scope, ie under src/main/java.

Thus I require additional goals / mojos to support this type of enhancement.  Following the conventions of the mvn-compile-plugin, I suggest 'test-enhance' and 'test-enhance-check'.

PR to follow.

**Comment by danhaywood** [comment]
NB: still on DataNucleus 4.1, so need this PR to be applied to the 4.0 code branch please.

**Comment by andyjefferson** [comment]
Not saying this isn't useful but can you not just set property "metadataDirectory" to ${project.build.testOutputDirectory} ???

**Comment by danhaywood** [comment]
Hmm.  OK, yes, that seemed to work.  I used:

	<groupId>org.datanucleus</groupId>
	<artifactId>datanucleus-maven-plugin</artifactId>
	<version>4.0.1</version>
	<configuration>
		<fork>false</fork>
		<log4jConfiguration>logging-dn-enhance.properties</log4jConfiguration>
		<verbose>true</verbose>
	</configuration>
	<executions>
		<execution>
			<id>process-classes</id>
			<phase>process-classes</phase>
			<goals>
				<goal>enhance</goal>
			</goals>
		</execution>
		<execution>
			<id>process-test-classes</id>
			<phase>process-test-classes</phase>
			<goals>
				<goal>enhance</goal>
			</goals>
			<configuration>
				<metadataDirectory>${project.build.testOutputDirectory}</metadataDirectory>
			</configuration>
		</execution>
	</executions>

As I'm unblocked, I don't care too much whether you apply the PR or reject it; I think on balance it's still worth having, but it's fairly marginal.
