### ISSUE TITLE
Datanucleus maven plugin v5.0.2

### ISSUE THREAD

**Issue by SerCeMan** [datanucleus/datanucleus-maven-plugin#8]
I found the fix for `test-enhance` (https://github.com/datanucleus/datanucleus-maven-plugin/issues/5) is very useful. Could you please release a new version of the plugin with this fix included?

**Comment by andyjefferson** [comment]
Things are released when they have been tested, and when they fit in with the timescales of people who contribute their time to this project. Consequently it will be released when it is released. That's why there are nightly builds etc.
